tuanuncio/home/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('',views.index.as_view(), name='index'),
    path('validation/',login_required(views.validation), name='validation' ),
    #path('publish/', views.pubList.as_view(), name='pubList'),
]

tuanuncio/publish/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required



urlpatterns = [
    path('publish/', login_required(views.pubList.as_view()), name='pubList'),
    path('publish/nuevo', login_required(views.pubCreate.as_view()), name='pubNuevo'),
    path('publish/update/<pk>', login_required(views.pubUpdate.as_view()), name='pubUpdate'),
    path('publish/delete/<pk>', login_required(views.pubDelete.as_view()), name='pubDelete'),

    
    #path('publish/', views.publish.as_view(), name='publish'),
    #path('',views.index.as_view(), name='index'),
]

tuanuncio/tuanuncio/urls.py
#from django.conf.urls import include, path
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ads/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('admin.urls')),
    path('',include('publish.urls')),
    path('accounts/', include('registration.backends.default.urls')),
    #url(r'^accounts/', include('registration.backends.default.urls')),
    
]

tuanuncio/publish/models.py
from django.db import models
from django.contrib.auth.models import User



import uuid

# Create your models here.

class region(models.Model):
    Codregion = models.CharField(max_length=2, default=None, primary_key=True)
    RegionName = models.CharField(max_length=50, default=None)
    
    def __str__(self):
        return self.RegionName
    
class comuna(models.Model):
    CodComuna = models.IntegerField(primary_key=True, default=None)
    Reg = models.ForeignKey(region, on_delete=models.CASCADE)
    ComunaName = models.CharField(max_length=50, default=None)

    def __str__(self):
        return self.ComunaName
class NameSocialNetworks(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    NameDescriptions = models.CharField(max_length=50, default=None)

    def __str__(self):
        return self.NameDescriptions

class social_networks(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user_socialNetwork = models.CharField(max_length=50)
    red = models.ManyToManyField(NameSocialNetworks, default=None)
    
    def __str__(self):
        return self.user_socialNetwork

class credits(models.Model): 
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date_recharge = models.TimeField
    amount = models.IntegerField()
    time_recharge = models.TimeField(auto_now=False, auto_now_add=False, default=None)
    #advertisement_id = models.ForeignKey(advertisement, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.amount)

class phones(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    typePhone = models.CharField(max_length=50)
    Number = models.CharField(max_length=12)
    wsp = models.BooleanField
    #advertisement_id = models.ForeignKey(advertisement, on_delete=models.CASCADE, default=None)
    def __str__(self):
        return self.Number


class typeA(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    description = models.CharField(max_length=50)
    #advertisement_id = models.ForeignKey(advertisement, on_delete=models.CASCADE, default=None)
    def __str__(self):
        return self.description

class subscription_plan(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    description = models.CharField(max_length=50)
    amount = models.IntegerField
    valid_from = models.DateField(auto_now=True, auto_now_add=False)
    valid_to = models.DateField(auto_now=False, auto_now_add=False)
    def __str__(self):
        return self.description

class advertisement(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    User = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    name = models.CharField(default = None, max_length=50, blank=True  )
    Type_advertisement = models.ForeignKey(typeA, on_delete=models.CASCADE, default=None)
    description  = models.CharField(max_length=200, default=None, blank=True  )    
    Userfacebook = models.CharField(default = None, max_length=50, blank=True  )
    UserInstagram = models.CharField(default = None, max_length=50, blank=True  )
    UserTwitter = models.CharField(default = None, max_length=50, blank=True  )
    # Social_network = models.ManyToManyField(social_networks, default=None)
    comuna = models.ForeignKey(comuna, on_delete=models.CASCADE, default = None)
    #phones = models.ManyToManyField(phones, default=None)
    whatsapp = models.CharField(max_length=11, default=None, blank=True  )
    show_phones = models.BooleanField(default=False, blank=True  )
    email = models.EmailField(max_length=254, default=None, blank=True  )                
    url_website = models.URLField(max_length=200, default=None, blank=True  )
    address = models.CharField(max_length=200, default=None, blank=True  )
    #latitude_longitude = models.CharField(max_length=200, default=None)
    show_adress = models.BooleanField(default=False, blank=True  )
    #image = models.ImageField(upload_to='static/img', default=None)
    #logo  = models.ImageField(upload_to='static/img/logo', default=None)
    incorporation_date = models.DateField(auto_now=True)
    #subscription_type = models.ForeignKey(subscription_plan, on_delete=models.CASCADE, default=None)
    state = models.BooleanField(default=False)
    #includes_maps  = models.BooleanField(default=False)
    #credits_id     = models.ForeignKey(credits, on_delete=models.CASCADE, default=None)
    #price_from = models.IntegerField(default=0)
    #price_to = models.IntegerField(default=0) 

    def __str__(self):
        return self.name

    def get_socialNetwork(self):
        return self.Social_network.name
        # return ', '.join([s.name for s in self.Social_network_set.all()])
    
    get_socialNetwork.shot_description = 'Redes Sociales'

HOUR_OF_DAY_24 = [(i,i) for i in range(1,25)]

WEEKDAYS = [
    (1, ("Lunes")),
    (2, ("Martes")),
    (3, ("Miercoles")),
    (4, ("Jueves")),
    (5, ("Viernes")),
    (6, ("Sabado")),
    (7, ("Domingo")),
]

class OpeningHours(models.Model):
    store = models.ForeignKey(advertisement, on_delete=models.CASCADE, default=None)
    weekday_from = models.PositiveSmallIntegerField(choices=WEEKDAYS, unique=True)
    weekday_to = models.PositiveSmallIntegerField(choices=WEEKDAYS)
    from_hour = models.PositiveSmallIntegerField(choices=HOUR_OF_DAY_24)
    to_hour = models.PositiveSmallIntegerField(choices=HOUR_OF_DAY_24)

    def get_weekday_from_display(self):
        return WEEKDAYS[self.weekday_from]

    def get_weekday_to_display(self):
        return WEEKDAYS[self.weekday_to]

class SpecialDays(models.Model):
    holiday_date = models.DateField()
    closed = models.BooleanField(default=True)
    from_hour = models.PositiveSmallIntegerField(choices=HOUR_OF_DAY_24, null=True, blank=True)
    to_hour = models.PositiveSmallIntegerField(choices=HOUR_OF_DAY_24, null=True, blank=True)

tuanuncio/publish/views.py
from django.shortcuts import render, redirect
from publish.models import advertisement
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django import forms
from django.urls import reverse_lazy
# Create your views here.

class pubList(ListView):
     model = advertisement
     template_name = 'publish/publish.html'

     def get_queryset(self):
          queryset = super(pubList, self).get_queryset()
          queryset = queryset.filter(User=self.request.user)

          return queryset

# def List(request):
#      #queryset = super(pubList, self).get_queryset()
#      #queryset = advertisement.objects.filter(User=request.user)[0]
#      #queryset = advertisement.objects.filter(User=request.user)#advertisement.objects.filter(User=request.user)[0]
#      # data = []
#      # for i in queryset:
#      #      dic = {
#      #           'id': i.id,
#      #           'User': i.User,
#      #           'name': i.name,
#      #           'Type_advertisement': i.Type_advertisement,
#      #           'description': i.description,
#      #           'Userfacebook': i.Userfacebook,
#      #           'UserInstagram': i.UserInstagram,
#      #           'UserTwitter': i.UserTwitter,
#      #           'comuna': i.comuna,
#      #           'whatsapp': i.whatsapp,
#      #           'show_phones': i.show_phones,
#      #           'email': i.email,
#      #           'url_website': i.url_website,
#      #           'address': i.address,
#      #           'show_adress': i.show_adress,
#      #           'incorporation_date': i.incorporation_date,
#      #           'state': i.state,
#      #           }
#      #      data.append(dic)
#      #      con['data'] = data
#      if request.user.is_superuser:
#           return(redirect('admList'))
#      else:
#           return(redirect('pubList'))

# class advCreate(CreateView):
#     model = advertisement
#     form_class = SchoolForm
#     template_name = 'publish/publish_form.html'
#     success_url = reverse_lazy('school_listar')

class pubCreate(CreateView):
     model = advertisement
     fields = ['User', 
               'name',
               'Type_advertisement',
               'description',
               'comuna',
               'whatsapp',
               'show_phones',
               'email',
               'url_website',
               'address',
               'show_adress', 
               'Userfacebook',
               'UserInstagram',
               'UserTwitter']

     template_name = 'publish/publish_form.html'
     success_url = reverse_lazy('pubList')

class pubUpdate(UpdateView):
     model = advertisement
     fields = ['User', 
               'name',
               'Type_advertisement',
               'description',
               'comuna',
               'whatsapp',
               'show_phones',
               'email',
               'url_website',
               'address',
               'show_adress', 
               'Userfacebook',
               'UserInstagram',
               'UserTwitter']
     template_name = 'publish/publish_form.html'
     success_url = reverse_lazy('pubList')
     
class pubDelete(DeleteView):
     model = advertisement
     template_name  = 'publish/publish_delete.html'
     success_url  = reverse_lazy('pubList')

tuanuncio/templates/publish/publish.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container">
<div class="float-right  d-none">
    <form class="form-inline ml-auto">
      <div class="md-form my-0">
        <input class="form-control" type="text" placeholder="Buscar" aria-label="Buscar">
      </div>
      <button href="#!" class="btn btn-outline-white btn-md my-0 ml-sm-2" type="submit">Buscar</button>
    </form>
 </div>   
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Categoria</th>
            <th>Descripcion</th>
            <th>Donde Ubicarlos</th>
            <th>Region</th>
            <th>Comuna</th>
            <th>Accion</th>
        </tr>
    </thead>
    <tbody>
        {% if object_list%} {% for adv in object_list %}
        <tr>
            <td>{{ adv.name }}</td>
            <td>{{adv.Type_advertisement}}</td>
            <td>{{ adv.description}}</td>
            <td>{{ adv.comuna }}</td>
            <td>{{ adv.comuna }}</td>
            <td>{{ adv.comuna }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'pubUpdate' adv.id  %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'pubDelete' adv.id  %}">Eliminar</a>
            </td>
        </tr>
        {% endfor %} {% else %}
        <h1>No hay emprendimientos que listar asociados a su cuenta</h1>
        <a class="btn btn-primary" href="{% url 'pubNuevo'  %}">Nuevo</a>
        {% endif %}
    </tbody>
</table>
</div>{% endblock content %}

tuanuncio/templates/publish/publish_delete.html
{% extends "base.html" %} {% block content %}
    <br>
<div class="container">
    <form method='post' enctype="multipart/form-data">
        {% csrf_token %} 
        <h3>¿Desea eliminar el registro de {{object.name}}?</h3>
        <button class="btn btn-danger" type="submit">Si</button>
        <a class="btn btn-primary" href="{% url 'pubList'%}">Cancelar</a>
    </form>
</div>

{% endblock %}

tuanuncio/templates/publish/publish_form.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}
{% block content %}
<br>
<div class="container">
    <form method='post' enctype="multipart/form-data" >
        {% csrf_token %} 
        <input type="hidden" name="User" class="form-control" id="id_User" value="{{user.id}}" readonly>
        {{form.name|as_crispy_field}}
        {{form.Type_advertisement|as_crispy_field}}
        {{form.description|as_crispy_field}}
        {{form.comuna|as_crispy_field}}
        {{form.whatsapp|as_crispy_field}}
        {{form.show_phones|as_crispy_field}}
        {{form.email|as_crispy_field}}
        {{form.url_website|as_crispy_field}}
        {{form.address|as_crispy_field}}
        {{form.show_adress|as_crispy_field}}
        {{form.Userfacebook|as_crispy_field}}
        {{form.UserInstagram|as_crispy_field}}
        {{form.UserTwitter|as_crispy_field}}
        <button type="submit">Guardar</button>
    </form>
</div>

{% endblock %}